# Generated by Django 5.2 on 2025-04-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient_names',
            new_name='ingrdient_order',
        ),
    ]
