# Generated by Django 5.2 on 2025-04-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredient_names_recipe_ingrdient_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingrdient_order',
        ),
    ]
